{% set data = load_setup_py_data() %}

package:
  name: ema_workbench
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipykernel
    - numpy
    - scipy >=1.2
    - pandas >=0.24
    - ipython
    - ipyparallel
    - scikit-learn
    - seaborn
    - matplotlib
    - pyzmq
    - platypus-opt
    - altair
    - pydot
    - dask
    - distributed
    - salib
    - statsmodels

build:
  noarch: python
  number: 1
  script: "python -m pip install . --no-deps -vv"

test:
  imports:
    - ema_workbench

about:
  home: https://github.com/jpn--/EMAworkbench
  license_file: LICENSE.md